import Head from 'next/head'
import {useRouter} from 'next/router'
export default function Header () {
    const router = useRouter()
    const path = router.asPath.replace('/', '').toUpperCase()
    return (
        <Head>
        <title>ForMyPhone {router.asPath === "/" ? null : `- ${path}`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}